[package]
name = "step_3_11"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.2.1", features=["derive"] }
futures = "0.3.28"
reqwest = "0.11.16"
tokio = { version = "1.27.0", features = ["full"] }
